### ISSUE TITLE
Perhaps oneTBB needs an update

### ISSUE THREAD

**Issue by KottV** [christofmuc/JammerNetz#31]
Hi!

included via gitmodules oneTBB fails to compile with gcc11 https://github.com/oneapi-src/oneTBB/issues/370
I've simply took the latest release of oneTBB https://github.com/oneapi-src/oneTBB/releases/tag/v2021.5.0 and JammerNerz has build and runs fine.

openSUSE Tumbleweed, g++ 11.2.1

**Comment by christofmuc** [comment]
@KottV Thanks! I'll update the oneTBB. The different versions of gcc make live harder on Linux...

**Comment by christofmuc** [comment]
Updated master branch to v2021.11.0 release now, builds with Linux on Azure Pipelines (which is Ubuntu 20.04 LTS).
This is the successful build's log: https://dev.azure.com/christof0759/JammerNetz/_build/results?buildId=582&view=logs&j=2f953adc-c56d-55c4-a64a-eab7c4b02235
