### ISSUE TITLE
Compilation on Linux

### ISSUE THREAD

**Issue by arnaudlecam** [christofmuc/JammerNetz#5]
Hi,
Compilation was fine with GCC 7.5.0 (Ubuntu 18.04), but failed with GCC 10.2.0 (Archlinux).
With GCC 10.2.0, flatbuffers' compilation fails with an Werror. It can be overided by:
- adding FLATBUFFERS_CXX_FLAGS cmake option (see [here](https://github.com/google/flatbuffers/pull/6429)) ;
- calling CMake with this option in `<JammerNetz>/third_party/flatbuffers`: `cmake -S . -B LinuxBuilds -G "Unix Makefiles" -D FLATBUFFERS_CXX_FLAGS="-Wno-error"`.

Perhaps informations could be given [here](https://github.com/christofmuc/JammerNetz#native-linux-builds) about your GCC version ?

**Comment by christofmuc** [comment]
Thank you! Yes, we haven't compiled our version for a while, and things like versions of gcc keep changing and be very divergent. I'll try to find out which versions we use (I compile in a docker container running on my Windows box to check the Linux build) and will add it to the docs!

**Comment by christofmuc** [comment]
I checked an indeed my build machine is based on Ubuntu and uses gcc 7.5.0. Will add this to the docs!

**Comment by christofmuc** [comment]
Great information, added the documentation for the command line switch and the version I test with to the README on master.
